### ISSUE TITLE
curl exit code 23 - failed writing body on demo

### ISSUE THREAD

**Issue by tim14smith** [AbsaOSS/spline-getting-started#18]
Following a change to make the containers run as unprivileged users, the latest version of the spline-rest-server image (0.7.7 at time of writing) fails to download the admin JAR. This appears to be because the unprivileged user does not have permission to write a file to the working directory.

This leads to the cryptic error which is a curl "failed writing body" code when trying to run the example from the readme.

```
downloading admin-cli
exit code: 23
```

**Comment by wajda** [comment]
@tim14smith can you try the updated `docker-compose.yml` from the PR #20, and see if it fixes the issue for you?

**Comment by tim14smith** [comment]
There wasn't an update for a while on the docker-compose.yml, meaning I was using the version on `main` [here (permalink)](https://github.com/AbsaOSS/spline-getting-started/tree/3a5c572df37b8d4684b35b293e791c9d727527b0/docker).

The docker-compose.yml from the PR fixed the issue! I was able to run the Getting Started using that setup.
