### ISSUE TITLE
Mac M1 chip cannot pull arangodb docker 

### ISSUE THREAD

**Issue by awarrior** [AbsaOSS/spline-getting-started#26]
<img width="627" alt="image" src="https://user-images.githubusercontent.com/9652304/186393935-3fa7b768-861d-4c2e-a8ff-3610d30b2879.png">
Hi, I try to deploy spline using my laptop but meet this error. What should I do next?

**Comment by cerveada** [comment]
Hi,

this is really question for arangodb team, not us.

After quick search I found this issue:
https://github.com/arangodb/arangodb/issues/13559

**Comment by awarrior** [comment]
Thx bro.
I have modified the yml file to add platform variable as one property of arangodb service config, like 
`platform: "linux/x86_64/v8"`
It works fine :)

**Comment by cerveada** [comment]
Also, ArangoDB 3.10 now supports ARM/M1 natively
