### ISSUE TITLE
how to configure kafka to collect lineage data so i can write a consumer to get it 

### ISSUE THREAD

**Issue by zacayd** [AbsaOSS/spline-getting-started#37]
Hi Alex 
My name is Zacay and I work  at Octopai
I succeeded to run a docker that holds - rest-API,webi-UI, arango and Kafak containers
my question is- how can I  listen to the topic of the kafka and get data from it?
what kind of data i can get on the topic messages?
Thanks in Advance
Zacay

**Comment by cerveada** [comment]
Hello Zacay,
- Issues are for reporting bugs and suggesting a features. To report bug you should be somewhat confident that what you are reporting is actually bug and not just wrong configuration or usage of the software.
- For questions and other discussions please use **Discussions** here on GitHub (not issues)
- What you write here is public, you are not writing to one specific person (like Alex)
- Spline team doesn't have the capacity to help with general (Spline unrelated) questions like "How to read from Kafka?". That is something you must learn yourself. We can only help with problems related to Spline.

I am closing this issue. If you have questions about spline please post them into discussions.
