### ISSUE TITLE
spline kafka for databricks

### ISSUE THREAD

**Issue by zacayd** [AbsaOSS/spline-getting-started#38]
Hi
i am using databricks spark jobs- i saw that you can configre properties to use kafka

```properties
spline.lineageDispatcher=kafka
spline.lineageDispatcher.kafka.producer.bootstrap.servers=192.168.100.11:9092
spline.lineageDispatcher.kafka.topic=foo
spark.spline.mode=REQUIRED
```

but i cannot see on kafak that a new topic was creaeted 
only a topic that was defined on the yml  config of the spline_spline-kafka container
my question is- can we have a littel phone call to understand this?
thanks in advanse
Zacay

**Comment by wajda** [comment]
> but i cannot see on kafak that a new topic was creaeted

there might be many reasons for this. First, make sure your Spline agent is working properly. Check logs. Use another dispatcher (e.g. `console` or `logging`) to make sure the lineage data is actually collected and printed. If yes, then the issue might indeed be related to either Kafka dispatcher or your Kafka cluster. Check logs, look for errors, warnings etc.

> my question is- can we have a littel phone call to understand this?

Unfortunately we do not have capacity to provide phone support.

**Comment by zacayd** [comment]
when i changed spark.spline.lineageDispatcher http
it workd and showed lineage on the UI
on the logs of the spline kafka container i got

ne-group-1, groupId=spline-group] Connection to node 1001 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
00:02:54.914 [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] WARN  o.apache.kafka.clients.NetworkClient - [Consumer clientId=consumer-spli### 

the topic is created but no messages in it

**Comment by cerveada** [comment]
Send the data via kafka dispatcher and check the topic.

**Comment by zacayd** [comment]
on databricks cluster i put
spline.lineageDispatcher kafka
spline.lineageDispatcher.kafka.producer.bootstrap.servers 192.168.100.11:9092
spline.lineageDispatcher.kafka.topic foo
spark.spline.mode REQUIRED

topic created but has no messages in it

**Comment by cerveada** [comment]
ok, please upload the log from the agent. I may be able to say what is wrong from that.

**Comment by zacayd** [comment]
where can it be? on the databricks?

**Comment by cerveada** [comment]
You need driver logs
https://stackoverflow.com/questions/69736416/where-to-find-spark-logs-in-databricks

**Comment by zacayd** [comment]
see here
[stdout--2022-11-28--15-00.txt](https://github.com/AbsaOSS/spline-getting-started/files/10104890/stdout--2022-11-28--15-00.txt)
[log4j-active (2).txt](https://github.com/AbsaOSS/spline-getting-started/files/10104891/log4j-active.2.txt)
[log4j-2022-11-28-14.log.gz](https://github.com/AbsaOSS/spline-getting-started/files/10104892/log4j-2022-11-28-14.log.gz)
[stderr--2022-11-28--15-00.txt](https://github.com/AbsaOSS/spline-getting-started/files/10104893/stderr--2022-11-28--15-00.txt)

**Comment by cerveada** [comment]
Fromt the log:
```
An error occurred while calling z:za.co.absa.spline.harvester.SparkLineageInitializer.enableLineageTracking.
: java.lang.NoClassDefFoundError: org/apache/kafka/clients/producer/KafkaProducer
```

Kafka libraries are missing. Include this:
https://mvnrepository.com/artifact/org.apache.kafka/kafka-clients/2.4.1

using `--packages` from here:
https://spark.apache.org/docs/latest/submitting-applications.html#advanced-dependency-management

**Comment by zacayd** [comment]
what i should do on databricks cluster?

**Comment by cerveada** [comment]
install the Kafka libraries using method 1
https://stackoverflow.com/questions/60543850/how-to-install-a-library-on-a-databricks-cluster-using-some-command-in-the-noteb

**Comment by cerveada** [comment]
The maven coordinates are in the link I provided yesterday.

**Comment by zacayd** [comment]
You can close this- i used my own Kafak
