### ISSUE TITLE
Spline needs 2nd address when deployed in k8s

### ISSUE THREAD

**Issue by van2142** [AbsaOSS/spline-getting-started#52]
Hello!
I trying to deploy Spline into k8s cluster via Helm instance, but when i open web-ui page, I get error, because browser try to load data from api service.
It turns out that 2 addresses are required for work in cluster, because api service not available out of cluster network.
I tried to get around this by mapping the Istio service to the subpath "/consumer" in the URl to access the API service but I get a 404 error
In k8s clusters we usually uses 1 addess to 1 instance.
![image](https://github.com/AbsaOSS/spline-getting-started/assets/140707275/be8a2a0d-02a9-4f06-b968-6b197931fb21)

**Comment by wajda** [comment]
You need to setup an ingress controller to make the REST API accessible outside of the kubernetes cluster
